spring.application.name=Backend
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
jwt.secret=cnchdaihdiw7ey327nwhdnkhcuichdcuyn87nhdbchdkvhyucnc78nce7y7wey37ycnhuchyw8ydvbufycbg2763287yqcnihduy73

# Google
spring.security.oauth2.client.registration.google.client-id=594377487113-2qf6bhptl72am65l1i0dajp7npi71141.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Facebook
spring.security.oauth2.client.registration.facebook.client-id=4409589369322598
spring.security.oauth2.client.registration.facebook.client-secret=63702771d11892b9bf689350c159576e
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}