spring.application.name=Backend
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
jwt.secret=cnchdaihdiw7ey327nwhdnkhcuichdcuyn87nhdbchdkvhyucnc78nce7y7wey37ycnhuchyw8ydvbufycbg2763287yqcnihduy73

spring.mvc.async.request-timeout=60000
server.tomcat.connection-timeout=60000

# Google
spring.security.oauth2.client.registration.google.client-id=594377487113-phlkh47mnaq0dca2l55olr3b3d585agt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Facebook
spring.security.oauth2.client.registration.facebook.client-id=4409589369322598
spring.security.oauth2.client.registration.facebook.client-secret=63702771d11892b9bf689350c159576e
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook